# Generated by Django 5.0.6 on 2025-07-09 04:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='date_limit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
