"""Contains constants"""
# Units in bytes
KB = 1024
MB = 1024 * KB
GB = 1024 * MB
TB = 1024 * GB

DATASET_MAX_SIZE = 10 * MB

TITLE_COLUMN="Title"
PILLAR_COLUMN="Pillar"
SUB_PILLAR_COLUMN="Sub pillar"
D2_PILLAR_COLUMN="2D column"
REQUIRED_COLUMNS=[TITLE_COLUMN,PILLAR_COLUMN,SUB_PILLAR_COLUMN,D2_PILLAR_COLUMN]
