name: Despliegue Automatico Terraform

on:
  push:
    branches: [ "feature/infra-terraform", "main" ]

jobs:
  deploy:
    name: 'Terraform Apply'
    runs-on: self-hosted # <--- Esto apunta a tu runner "PersonalUbuntuServer"

    defaults:
      run:
        working-directory: ./infra_terraform

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
