# Generated by Django 5.0.6 on 2025-04-24 12:38

import common.models.base_model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_url', models.URLField(max_length=2000)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('other', 'Other')], max_length=20)),
                ('file_size', models.FloatField(blank=True, help_text='File size in bytes.', null=True)),
                ('file_format', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'db_table': 'media_file',
            },
            bases=(models.Model, common.models.base_model.BaseModel),
        ),
    ]
