# Generated by Django 5.0.6 on 2025-07-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
