name: Despliegue Real Terraform
on:
  push:
    branches: [ "feature/infra-terraform" ]

jobs:
  terraform-deploy:
    runs-on: self-hosted
    steps:
      - name: Descargar Código
        uses: actions/checkout@v4

      - name: Ejecutar Terraform
        run: |
          cd infra_terraform
          terraform init
          terraform apply -auto-approve
